### ISSUE TITLE
unbound host override update fails when fields are not changing

### ISSUE THREAD

**Issue by silviuvulcan** [jaredhendrickson13/pfsense-api#26]
First thanks for this ! pfsense need this for ages.

I'm using this inside ansible to keep internal dns overrides up to date for a bunch of hosts. I added logic to determine if it's an update or a new override (personally I would have loved to simply set the override and let the backend decide if it's new or update) but I still get failures when there are no actual updates.

I would expect it to work even if nothing changes. I run it like this:

```
      - name: update unbound override for {{ inventory_hostname }}
        uri:
          url: "https://1.2.3.4/api/v1/services/unbound/host_override"
          method: PUT
          body:
            client-id: "{{ client_id }}"
            client-token: "{{ client_token }}"
            id: "{{ item_index }}"
            domain: example.com
            ip: "{{ base_vlan_net_ifaces[0].ip }}"
          body_format: json
```

Unless there's a change in the domain name it fails. Funily enough PUTing only the ip works even if there are no changes...

```
fatal: [localhost]: FAILED! => changed=false 
  connection: close
  content_type: application/json
  date: Fri, 30 Oct 2020 15:35:36 GMT
  elapsed: 0
  json:
    code: 400
    data: []
    message: Unbound host override already exists
    return: 2010
    status: bad request
  msg: 'Status code was 400 and not [200]: HTTP Error 400: Bad Request'
  redirected: false
  referer: no-referrer
  server: nginx
  status: 400
  transfer_encoding: chunked
  url: https://1.2.3.4/api/v1/services/unbound/host_override
```

Edit: please ignore the now removed comment, I was calling the api with a missing parameter.
