### ISSUE TITLE
Is it me or API token authentication is broken in pfsense 2.7.0?

### ISSUE THREAD

**Issue by filviu** [jaredhendrickson13/pfsense-api#383]
**Describe the bug**
Both api/documentation/ and ansible/curl give me `msg: 'Status code was 401 and not [200]: HTTP Error 401: Unauthorized'` on various endpoints. I tried various GET endpoints and same issue.

**To Reproduce**
Try any endoint wiht API token auth

**Expected behavior**
-

**Screenshots or Response**
-

**pfSense Version & Package Version:**
 - pfSense Version: [pfSense 2.7.0]
 - Package Version [v1.6.0]

**Affected Endpoints:**
- all

**Additional context**
- My user is admin
- I tried rotating server key and api key. 
- If I switch to local database authentication the it works using user+pass

I'm not saying this is a bug - just let me know if I'm the only one and I can keep digging :D

Thanks!

**Comment by jaredhendrickson13** [comment]
Hey!

Token auth seems to be working for me on a fresh install of pfSense 2.7.0 and API v1.6.1. I'm assuming you are obtaining the token using the steps outlined in #103. Any chance you can provide the request syntax you are using from Ansible or curl?

Thanks!

**Comment by filviu** [comment]
Found the issue. 

In ansible I was using:

```yaml
    - name: Get existing overrides
      ansible.builtin.uri:
        url: "{{ pf_url }}/api/v1/services/unbound/host_override"
        status_code: [200]
        method: "GET"
        body:
          client-id: "{{ client_id }}"
          client-token: "{{ client_token }}"
        body_format: json
        validate_certs: no
      register: host_override
```

Today it should look like this:

```yaml
    - name: Get existing overrides
      ansible.builtin.uri:
        url: "{{ pf_url }}/api/v1/services/unbound/host_override"
        status_code: [200]
        method: "GET"
        headers:
          Authorization: "{{ client_id }} {{ client_token }}"
        body_format: json
        validate_certs: no
      register: host_override
```

What was throwing me off (and I wasn't careful either) is that the curl snippet that `/api/documentation/` generates is missing the client id:

```
curl -X 'GET' \
  'https://pfsense.example.com:8443/api/v1/services/unbound/host_override' \
  -H 'accept: application/json' \
  -H 'Authorization: xxxxxxxxxx_token_xxxxxxxxxxxx'
```

It should be: `  -H 'Authorization: 6xxxx_ID_xxxx xxxxxxxxxx_token_xxxxxxxxxxxx'`

As far as I can tell there's no way to enter the client id in `/api/documentation/`

Thanks for setting me on the right track 😄
